from .recenseador import Recenseador
from .domicilio import Domicilio
from .genero import Genero
from .estado_civil import EstadoCivil
from .parentesco import Parentesco
from .grau_escolaridade import GrauEscolaridade
from .situacao_trabalho import SituacaoTrabalho
from .tipo_residencia import TipoResidencia
from .acesso_servico import AcessoServico
from .questionario import Questionario
from .questionario_acesso_servico import QuestionarioAcessoServico
